module.exports = {
  WIT_TOKEN: process.env.WIT_TOKEN || '7DBSLYZEHB2ZXLZE63MBZYYZU5VQKM2F',
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN || '1012381439:AAHiLlWfgCNRpngZVHD3jCpj4KYWK4TNAPk'
};
